# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget szip-static szip-shared)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target szip-static
add_library(szip-static STATIC IMPORTED)

# Create imported target szip-shared
add_library(szip-shared SHARED IMPORTED)

set_target_properties(szip-shared PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SZ_BUILT_AS_DYNAMIC_LIB=1"
)

# Import target "szip-static" for configuration ""
set_property(TARGET szip-static APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(szip-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "F:/v3d_mingw1/v3d_external/v3d_main/common_lib/src_packages/szip-2.1.1/bin/libszip-static.a"
  )

# Import target "szip-shared" for configuration ""
set_property(TARGET szip-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(szip-shared PROPERTIES
  IMPORTED_IMPLIB_NOCONFIG "F:/v3d_mingw1/v3d_external/v3d_main/common_lib/src_packages/szip-2.1.1/bin/szip-shared.lib"
  IMPORTED_LOCATION_NOCONFIG "F:/v3d_mingw1/v3d_external/v3d_main/common_lib/src_packages/szip-2.1.1/bin/szip-shared.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
