
FIND_PATH(FFTW3_INCLUDE_DIR fftw3.h
  /usr/local/include
  /usr/include
)

FIND_LIBRARY(FFTW3_LIBRARY fftw3
  /usr/lib
  /usr/local/lib
)

SET(FFTW3_FOUND FALSE)
IF(FFTW3_INCLUDE_DIR AND FFTW3_LIBRARY)
    SET(FFTW3_LIBRARIES ${FFTW3_LIBRARY} )
    SET(FFTW3_FOUND TRUE)
ENDIF(FFTW3_INCLUDE_DIR AND FFTW3_LIBRARY)

MARK_AS_ADVANCED(
  FFTW3_INCLUDE_DIR
  FFTW3_LIBRARIES
  FFTW3_FOUND
  )
