
FIND_PATH(LEVMAR_INCLUDE_DIR lm.h
  /usr/local/include
  /usr/include
)

FIND_LIBRARY(LEVMAR_LIBRARY levmar
  /usr/lib
  /usr/local/lib
)

SET(LEVMAR_FOUND FALSE)
IF(LEVMAR_INCLUDE_DIR AND LEVMAR_LIBRARY)
    SET(LEVMAR_INCLUDE_DIRS ${LEVMAR_INCLUDE_DIR} )
    SET(LEVMAR_LIBRARIES ${LEVMAR_LIBRARY} )
    SET(LEVMAR_FOUND TRUE)
ENDIF(LEVMAR_INCLUDE_DIR AND LEVMAR_LIBRARY)

MARK_AS_ADVANCED(
  LEVMAR_INCLUDE_DIR
  LEVMAR_LIBRARIES
  LEVMAR_FOUND
  )
