TEMPLATE      = lib
CONFIG       += qt plugin warn_off
INCLUDEPATH  += ../../../v3d_main/basic_c_fun
HEADERS      +=../../../v3d_main/basic_c_fun/basic_surf_objs.h
HEADERS      += Canny.h
SOURCES      +=../../../v3d_main/basic_c_fun/basic_surf_objs.cpp
SOURCES      += Canny.cpp
SOURCES      += ../../../v3d_main/basic_c_fun/v3d_message.cpp
TARGET        = $$qtLibraryTarget(Canny)
DESTDIR       = ../../../v3d/plugins/Canny
