// This file has been generated by Py++.

#ifndef _LocationSimple__value_traits_pypp_hpp_hpp__pyplusplus_wrapper
#define _LocationSimple__value_traits_pypp_hpp_hpp__pyplusplus_wrapper

namespace boost { namespace python { namespace indexing {

template<>
struct value_traits< LocationSimple >{

    static bool const equality_comparable = true;
    typedef std::equal_to< LocationSimple > equal_to;

    static bool const less_than_comparable = false;
    

    template<typename PythonClass, typename Policy>
    static void visit_container_class(PythonClass &, Policy const &){
        
    }

};

}/*indexing*/ } /*python*/ } /*boost*/

#endif//_LocationSimple__value_traits_pypp_hpp_hpp__pyplusplus_wrapper
