// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrappable_v3d.h"
#include "convert_c_array_struct.h"
#include "c_array_short_3.pypp.hpp"

namespace bp = boost::python;

void register_c_array_short_3_class(){

    bp::class_< c_array< short, 3 > >( "c_array_short_3", "\n Light wrapper for C-arrays, to make them easier\n to expose in python.\n\n Runtime performance should not be affected.\n" )    
        .def( 
            "__getitem__"
            , (short int const & ( ::c_array<short, 3>::* )( int ) const)( &::c_array< short, 3 >::operator[] )
            , ( bp::arg("i") )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "__getitem__"
            , (short int & ( ::c_array<short, 3>::* )( int ) )( &::c_array< short, 3 >::operator[] )
            , ( bp::arg("i") )
            , bp::return_value_policy< bp::copy_non_const_reference >() )    
        .def( 
            "size"
            , (int (*)(  ))( &::c_array< short, 3 >::size ) )    
        .staticmethod( "size" )    
        .def(bp::indexing::container_suite<
                            c_array<short, 3>, bp::indexing::all_methods,
                            list_algorithms<c_array_struct_container_traits< c_array<short, 3> > > >());

}
