// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrappable_v3d.h"
#include "QBool.pypp.hpp"

namespace bp = boost::python;

void register_QBool_class(){

    { //::QBool
        typedef bp::class_< QBool > QBool_exposer_t;
        QBool_exposer_t QBool_exposer = QBool_exposer_t( "QBool", bp::init< bool >(( bp::arg("B") )) );
        bp::scope QBool_scope( QBool_exposer );
        bp::implicitly_convertible< bool, QBool >();
        QBool_exposer.def( "as_void_const__ptr_", &QBool::operator void const * ,bp::return_value_policy< bp::return_opaque_pointer >() );
    }

}
