// This file has been generated by Py++.

#ifndef QList_LocationSimple_hpp__pyplusplus_wrapper
#define QList_LocationSimple_hpp__pyplusplus_wrapper

void register_QList_LocationSimple_class();

#endif//QList_LocationSimple_hpp__pyplusplus_wrapper
