// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrappable_v3d.h"
#include "RGB8.pypp.hpp"

namespace bp = boost::python;

void register_RGB8_class(){

    bp::class_< RGB8 >( "RGB8" )    
        .def_readwrite( "b", &RGB8::b )    
        .def_readwrite( "g", &RGB8::g )    
        .def_readwrite( "r", &RGB8::r );

}
