// This file has been generated by Py++.

#ifndef std_list_LocationSimple_hpp__pyplusplus_wrapper
#define std_list_LocationSimple_hpp__pyplusplus_wrapper

void register_std_list_LocationSimple_class();

#endif//std_list_LocationSimple_hpp__pyplusplus_wrapper
