// This file has been generated by Py++.

#include "boost/python.hpp"
#include "indexing_suite/container_suite.hpp"
#include "indexing_suite/list.hpp"
#include "wrappable_v3d.h"
#include "_LocationSimple__value_traits.pypp.hpp"
#include "std_list_LocationSimple.pypp.hpp"

namespace bp = boost::python;

void register_std_list_LocationSimple_class(){

    bp::class_< std::list< LocationSimple > >("std_list_LocationSimple")    
        .def( bp::indexing::list_suite< std::list< LocationSimple > >() );

}
