#ifndef __CGS_SETTINGS__

#define __CGS_SETTINGS__
#define CGS_AUTOLAUNCH 1
#define V3D_SKIP_AUTO_VERSION_CHECK 1
#define RENDERER_RIGHT_CLICK_MENU_DISABLED 1
#define HIDE_ANO_TOOLBAR 1
#define UNREVERSE_MOUSE_WHEEL_ZOOM 1
#define FORCE_BBOX_MODE 1

#endif